"""empty message

Revision ID: 36d638174579
Revises: e2e1ef9e7f70
Create Date: 2020-05-20 02:42:33.735099

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36d638174579'
down_revision = 'e2e1ef9e7f70'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('times', sa.Column('escudo', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('times', 'escudo')
    # ### end Alembic commands ###
