"""empty message

Revision ID: e2e1ef9e7f70
Revises: 0f7b21c18ba5
Create Date: 2020-05-12 11:23:05.411609

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2e1ef9e7f70'
down_revision = '0f7b21c18ba5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('times',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_times_nome'), 'times', ['nome'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_times_nome'), table_name='times')
    op.drop_table('times')
    # ### end Alembic commands ###
